# This is a basic workflow to help you get started with Actions

name: Production Workflow CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.14.x]
     
     # Steps is a set of tasks to be completed in sequential order 
    steps:
   
      # Use the node version specified in the strategy    
      - name: Use Node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v1      
        with:        
          node-version: ${{ matrix.node-version }}
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2
